Restaurant.create(name: "Mangia", description: "awesome place to eat", city: "New Jersey", star_rating: 5, cuisine: "Italian")
Restaurant.create(name: "Roots", description: "fine dining", city: "Norristown", star_rating: 3, cuisine: "Everything")
Restaurant.create(name: "Mino", description: "best sushi ever", city: "Philly", star_rating: 5, cuisine: "Asian")
Restaurant.create(name: "Pats & Ginos", description: "great cheesesteaks", city: "Philly", star_rating: 4, cuisine: "Steaks")
Restaurant.create(name: "El Meson", description: "pretty good food", city: "New Jersey", star_rating: 2, cuisine: "Mexican")